# Module 6 - Correlation & Linear Regression

In [1]:
import pandas as pd
import numpy as np

## Correlation

In [2]:
Location = "nyc-rolling-sales.csv"
df = pd.read_csv(Location)

df.head()

,Unnamed: 0,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASE-MENT,BUILDING CLASS AT PRESENT,ADDRESS,...,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,4,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,392,6,,C2,153 AVENUE B,...,5,0,5,1633,6440,1900,2,C2,6625000,2017-07-19 00:00:00
1,5,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,26,,C7,234 EAST 4TH STREET,...,28,3,31,4616,18690,1900,2,C7,-,2016-12-14 00:00:00
2,6,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2,399,39,,C7,197 EAST 3RD STREET,...,16,1,17,2212,7803,1900,2,C7,-,2016-12-09 00:00:00
3,7,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2B,402,21,,C4,154 EAST 7TH STREET,...,10,0,10,2272,6794,1913,2,C4,3936272,2016-09-23 00:00:00
4,8,1,ALPHABET CITY,07 RENTALS - WALKUP APARTMENTS,2A,404,55,,C2,301 EAST 10TH STREET,...,6,0,6,2369,4615,1900,2,C2,8000000,2016-11-17 00:00:00

In [3]:
df.corr()

,Unnamed: 0,BOROUGH,BLOCK,LOT,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,YEAR BUILT,TAX CLASS AT TIME OF SALE
Unnamed: 0,1.000000,0.088817,0.264130,-0.031601,0.166882,-0.013318,-0.002821,-0.012856,-0.004057,0.017395
BOROUGH,0.088817,1.000000,0.417001,-0.277848,0.256564,-0.023229,-0.005503,-0.023346,0.108303,-0.315163
BLOCK,0.264130,0.417001,1.000000,-0.229118,0.234063,-0.015628,-0.003517,-0.015888,0.071262,-0.287300
LOT,-0.031601,-0.277848,-0.229118,1.000000,-0.145802,-0.034303,-0.010953,-0.033169,-0.289463,0.296680
ZIP CODE,0.166882,0.256564,0.234063,-0.145802,1.000000,0.005578,0.000726,0.005415,0.330708,-0.142915
RESIDENTIAL UNITS,-0.013318,-0.023229,-0.015628,-0.034303,0.005578,1.000000,0.015653,0.888309,0.025380,-0.001074
COMMERCIAL UNITS,-0.002821,-0.005503,-0.003517,-0.010953,0.000726,0.015653,1.000000,0.472998,0.006428,0.049586
TOTAL UNITS,-0.012856,-0.023346,-0.015888,-0.033169,0.005415,0.888309,0.472998,1.000000,0.024568,0.026429
YEAR BUILT,-0.004057,0.108303,0.071262,-0.289463,0.330708,0.025380,0.006428,0.024568,1.000000,-0.187609
TAX CLASS AT TIME OF SALE,0.017395,-0.315163,-0.287300,0.296680,-0.142915,-0.001074,0.049586,0.026429,-0.187609,1.000000

## Linear Regression

In [4]:
import statsmodels.formula.api as smf

In [5]:
df["ZIP_CODE"]=df["ZIP CODE"]
df["YEAR_BUILT"]=df["YEAR BUILT"]
df["RESIDENTIAL_UNITS"]=df["RESIDENTIAL UNITS"]
df["COMMERCIAL_UNITS"]=df["COMMERCIAL UNITS"]

In [6]:
result = smf.ols('ZIP_CODE ~ YEAR_BUILT + RESIDENTIAL_UNITS + COMMERCIAL_UNITS', data=df).fit()

In [7]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               ZIP_CODE   R-squared:                       0.109
Model:                            OLS   Adj. R-squared:                  0.109
Method:                 Least Squares   F-statistic:                     3461.
Date:                Sat, 02 Mar 2019   Prob (F-statistic):               0.00
Time:                        13:18:10   Log-Likelihood:            -7.2070e+05
No. Observations:               84548   AIC:                         1.441e+06
Df Residuals:                   84544   BIC:                         1.441e+06
Df Model:                           3
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept          9310.5644     14.568    639.110      0.000    9282.011    9339.118
YEAR_BUILT            0.7947      0.008    101.882      0.000       0.779       0.810
RESIDENTIAL_UNITS    -0.2159      0.251     -0.861      0.389      -0.707       0.275
COMMERCIAL_UNITS     -0.2010      0.481     -0.418      0.676      -1.144       0.742
==============================================================================
Omnibus:                    87355.265   Durbin-Watson:                   0.715
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          5693453.141
Skew:                          -5.226   Prob(JB):                         0.00
Kurtosis:                      41.819   Cond. No.                     6.50e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.5e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

With age, exercise, and hours being 0, your starting grade is likely to be around 57.87

In [ ]:
#remove age from regression, not very correlated
result = smf.ols('grade ~ exercise + hours', data=df).fit()
result.summary()

In [ ]:
#set coefficient to 0
result = smf.ols(formula='grade ~ age + exercise + hours - 1', data=df).fit()
result.summary()

### Your Turn

Run a correlation and regresssion on the dataset below. What can you tell from the data?

In [ ]:
Location = "datasets/datasets/tamiami.csv"

df = pd.read_csv(Location)
df.head()

In [ ]:
columns = ['location', 'sales', 'employees', 'restaurants', 'foodcarts', 'price']

#change column names for readability
df.columns = columns
df.head()